# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# 
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Computing Fundamentals & Programming CE
subjectName: Computing Fundamentals & Programming
tagline: Fall 2021- CE100 - CFP #Update Tag Line & URL at line no 21 & CNAME File #Fall 2022 - CE200 - DSA
description: This introductory course is aimed at the students with little or no programming experience, and it introduces students to the basics of computers and programming. On one hand they will learn basic topics of computing and usage, while on the other hand they will be exposed to programming language(s). By the end of course the student should be capable of programming in at least one programming language.
author: Usama Bin Shakeel
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://fall2021-ce100.ubs.dev'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
logo: "/assets/images/ubs-itu.png"
exclude: [vendor]
# Theme settings
remote_theme: pmarsceill/just-the-docs@v0.3.3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Usama Bin Shakeel:
    - 'https://ubs.dev'

footer_content:
# Collections for website data
collections:
  staffers:
  modules:
  students:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/staff/'
  - scope:
      path: ''
      type: students
    values:
      layout: staffer
      subpath: '/assets/images/students/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-cayman